### ISSUE TITLE
Why we can't search by id?

### ISSUE THREAD

**Issue by ionutpopa** [DomDew/strapi-plugin-fuzzy-search#164]
I want to build a search that works by searching the name, id or both id with name but I get Key: 'id' is not a valid field for model: 'my-model.
So the question is easy: why can't we search by id as well?

**Comment by DomDew** [comment]
Hey @ionutpopa, the reason is that the search will run a fuzzy search against each key that is specified in the config and that is present in the `attributes` key for a given content type (the validation makes sure that the key is a valid attribute). The information about the content type and its attributes is obtained via Strapi internals. The `id` key is not part of the `attributes` though.

Including the id field as well would require a bigger refactor and would add some noise and clutter to the codebase. I don't see many use cases for running a fuzzy search against an id field and thus I don't think the added complexity would be worth it, I'm sorry.
