### ISSUE TITLE
Error on startup with new strapi version

### ISSUE THREAD

**Issue by corentingosselin** [DomDew/strapi-plugin-fuzzy-search#18]
Hey,

It seems fuzzy does not start with version 4.3.2:

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/8132994/183266533-bb03510b-c4b0-4988-a53c-bbbfb5cc360a.png">

**Comment by DomDew** [comment]
Hey @corentingosselin, 

I think this might be an issue with how you set up the fuzzy search plugin in the plugins.js. From what I can gather, this error is telling you that you passed an object ("{}") to the contentTypes key, yet this key is expecting an array. 

Throwing this is error is the expected behaviour of the plugin, as we are validating the configuration object passed to the plugin on launch.

I think if you set the contentTypes array to an array everything should work as expected. For reference [have a look at the example config](https://github.com/DomDew/strapi-plugin-fuzzy-search#full-example-config).

**Comment by corentingosselin** [comment]
Thanks !
forgot that config part, also forgot to build ;)
